### ISSUE TITLE
VS 2017 15.7.4 error

### ISSUE THREAD

**Issue by aguacongas** [MrLuje/vs-commitizen#13]
Using VS 2017 15.7.4, I've this issue when I click the CommitCz button:

```
Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "vs_commitizen.vs2015.VsCommitizenSection". ---> StructureMap.StructureMapConfigurationException: No default Instance is registered and cannot be automatically determined for type 'vs_commitizen.vs.Settings.IUserSettings'

There is no configuration specified for vs_commitizen.vs.Settings.IUserSettings

1.) new CommitizenViewModel(*Default of IUserSettings*)
2.) vs_commitizen.vs.ViewModels.CommitizenViewModel
3.) Instance of vs_commitizen.vs.ViewModels.CommitizenViewModel
4.) Container.GetInstance<vs_commitizen.vs.ViewModels.CommitizenViewModel>()

   at lambda_method(Closure , IBuildSession , IContext )
   at StructureMap.Building.BuildPlan.Build(IBuildSession session, IContext context)
   at StructureMap.BuildSession.BuildNewInSession(Type pluginType, Instance instance)
   at StructureMap.Pipeline.NulloTransientCache.Get(Type pluginType, Instance instance, IBuildSession session)
   at StructureMap.BuildSession.ResolveFromLifecycle(Type pluginType, Instance instance)
   at StructureMap.SessionCache.GetObject(Type pluginType, Instance instance, ILifecycle lifecycle)
   at StructureMap.SessionCache.GetDefault(Type pluginType, IPipelineGraph pipelineGraph)
   at StructureMap.Container.GetInstance[T]()
   at vs_commitizen.Settings.IoC.GetInstance[T]()
   at vs_commitizen.vs.VsCommitizenView..ctor()
   at vs_commitizen.vs2015.VsCommitizenSection..ctor()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass53_0.<CreateExport>b__0()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass55_0.<CreateExportFactoryExport>b__1()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass54_0.<CreateExportFactory>b__0()
   at Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0()
   at System.ComponentModel.Composition.ExportFactory`1.CreateExport()
   at Microsoft.VisualStudio.Composition.NetFxAdapters.MefV1ExportProvider.ComposablePartDefinitionForExportFactory.CreatePart()
   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.LifetimeContext.GetExportLifetimeContextFromExport[T](Export export)
   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.<>c__DisplayClass6_0`2.<CreateStronglyTypedExportFactoryOfTM>b__0()
   at System.ComponentModel.Composition.ExportFactory`1.CreateExport()
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Create()
```
#12 seems not to be fixed

**Comment by aguacongas** [comment]
My git repository wasn't correctly setuped, that cause the issue
