### ISSUE TITLE
Visual Studio crashes in most cases when opening Team Explorer

### ISSUE THREAD

**Issue by doormalena** [MrLuje/vs-commitizen#21]
**Describe the bug**
Visual Studio crashes sometimes when opening Team Explorer after just starting up Visual Studio.
My fellow team mates have the same behavior on their machines from time to time. Could it be performance related? When repeating the steps from the reproduction it will not crash after a few retries.

Eventlog shows .NET Runtime error:

> Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Microsoft.VisualStudio.Shell.ThreadHelper.get_JoinableTaskContext()
   at vs_commitizen.vs2015.VsCommitizenNavigationItem+<UpdateIsVisibleAsync>d__4.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at vs_commitizen.vs2015.VsCommitizenNavigationItem+<GitService_PropertyChanged>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**To Reproduce**
1. Start Visual Studio
2. Open Recent project (in this case hosted on Azure DevOps / Git-repo)
3. Click Connect in the (authentication) dialog that is opening up.

**Expected behavior**
No crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/8328876/63854014-6ea68a00-c99c-11e9-919b-f4b3f7e105cd.png)

**Visual Studio (please complete the following information):**
 - Professional or Enterprise (same behavior)
 - 2019 / 16.2.3

**Comment by MrLuje** [comment]
Ah, never ran into that one...

> Could it be performance related?

Yep, could be... since most VS Package logic should be async, I guess I'm trying to access non-ready UI stuff at this point (even I am properly awaiting the UI thread with _ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync()_ 😩)

I'll have a look

**Comment by MrLuje** [comment]
You can give a try to [this version](https://ci.appveyor.com/api/buildjobs/n3ps6oxqq72hvdta/artifacts/vs-commitizen%2Fbin%2FRelease%2Fvs-commitizen.vsix)

**Comment by doormalena** [comment]
Thanks for your effort! 
Just tested it. VS keeps crashing unfortunately.

![image](https://user-images.githubusercontent.com/8328876/64253259-2e578680-cf1d-11e9-9be3-b1b6b03cab75.png)

**Comment by MrLuje** [comment]
[one more ](https://ci.appveyor.com/api/buildjobs/fro5rc0t0k3l7ajd/artifacts/vs-commitizen%2Fbin%2FRelease%2Fvs-commitizen.vsix)

Do you have other extensions, beside this one, in common with your teammate that impacts "Team Explorer" view ?

**Comment by doormalena** [comment]
This version seems promising. It did not make VS crash after first startup. I will continue to do some startup tests today.

In regards to your question: yes we have multiple other extensions installed which we have in common:
- R#
- PowerShell Tools for Visual Studio
- ReAttach
- Visual Studio Spell Checker (VS2017 and Later)
- HSR Parallel Checker for C#
- Productivity Power Tools 2017/2019

Whether they are impacting the Team Explorer view I don't know at this time.

**Comment by doormalena** [comment]
Strange. First 2 tests where OK. Now it constantly crashes again.

**Comment by MrLuje** [comment]
Ok, [new one ](https://ci.appveyor.com/api/buildjobs/471hcbv65m8p4qgq/artifacts/vs-commitizen%2Fbin%2FRelease%2Fvs-commitizen.vsix): it should prevent any crashing and will instead log the error in output panes

![image](https://user-images.githubusercontent.com/632075/64266284-a41b1c80-cf34-11e9-93d6-611228187a38.png)

**Comment by doormalena** [comment]
I does not make much of a difference, it keeps crashing with the same error. I cannot see the output pane as well, am I missing something?

![image](https://user-images.githubusercontent.com/8328876/64313701-c3ee2700-cfac-11e9-8f04-dcd26548561a.png)

**Comment by MrLuje** [comment]
If [this one](https://ci.appveyor.com/api/buildjobs/ur7p99ej6chyx6h6/artifacts/vs-commitizen%2Fbin%2FRelease%2Fvs-commitizen.vsix) doesn't prevent the crash, I'll probably need a crash dump to have more insights about it

**Comment by doormalena** [comment]
I have a [crash dump](https://wetransfer.com/downloads/563eaeec790e196866acc2b937bf411920190905144404/7d75ab2af62a1e194bd66ec29e79bf2c20190905144404/8d738f) for you unfortunately.

**Comment by bvirkler** [comment]
I'm getting the same crashes.  (Love this extension otherwise!)

**Comment by aguacongas** [comment]
Same crash after commited the code using VS 2019 16.5.4. The stack trace is a little bit different :

```bash
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at vs_commitizen.vs2015.VsCommitizenNavigationItem.UpdateIsVisibleAsync()
   at vs_commitizen.vs2015.VsCommitizenNavigationItem+<GitService_PropertyChanged>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by MrLuje** [comment]
The "System.IO.FileNotFoundException" bug is fixed in the new release (but I don't think it will address the original issue)
